# Maps for code mime types and extensions

code_mime_types = {
    ".py": "text/x-python",
    ".js": "application/javascript",
    ".ts": "application/typescript",
    ".tsx": "application/typescript",
    ".jsx": "application/javascript",
    ".java": "text/x-java-source",
    ".cpp": "text/x-c++src",
    ".c": "text/x-csrc",
    ".h": "text/x-chdr",
    ".hpp": "text/x-c++hdr",
    ".cs": "text/x-csharp",
    ".go": "text/x-go",
    ".rb": "text/x-ruby",
    ".php": "text/x-php",
    ".pl": "text/x-perl",
    ".sh": "application/x-sh",
    ".swift": "text/x-swift",
    ".scala": "text/x-scala",
    ".lua": "text/x-lua",
    ".f90": "text/x-fortran",
    ".f95": "text/x-fortran",
    ".erl": "text/x-erlang",
    ".exs": "text/x-elixir",
    ".bat": "application/x-bat",
    ".sql": "application/sql",
    ".lisp": "text/x-common-lisp",
    ".vb": "text/x-vb",
    ".ipynb": "application/x-ipynb+json",
    ".xml": "application/xml",
    ".yml": "text/yaml",
    ".yaml": "text/yaml",
    ".json": "application/json",
    ".kt": "text/x-kotlin",
    ".rst": "text/x-rst",
    ".html": "text/html",
}

code_extensions = set(code_mime_types.keys())