
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-09T13:20:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "99634713dd2ccccae749f2febe7d8d244e8452fd",
 "version": "25.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
