# Generated by Django 3.2.19 on 2023-06-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_webhooks', '0003_auto_20230607_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='webfilter',
            name='use_www_form_encoding',
            field=models.BooleanField(default=False, help_text='When enabled, data will be sent in form format, instead of JSON', verbose_name='Use WWW form encoding'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='use_www_form_encoding',
            field=models.BooleanField(default=False, help_text='When enabled, data will be sent in form format, instead of JSON', verbose_name='Use WWW form encoding'),
        ),
        migrations.AlterField(
            model_name='webfilter',
            name='disable_halt',
            field=models.BooleanField(default=False, help_text="Don't stop the process even if the response includes exception data.", verbose_name='Disable halting'),
        ),
    ]
