"""
This type stub file was generated by pyright.
"""

import threading

"""
Utilities helpful for writing tests

Provides a UnixSocketServerThread that creates a running server, listening on a
newly created unix socket.

Example usage:

.. code-block:: python

    def test_unix_domain_adapter_monkeypatch():
        with UnixSocketServerThread() as usock_thread:
            with requests_unixsocket.monkeypatch('http+unix://'):
                urlencoded_usock = quote_plus(usock_process.usock)
                url = 'http+unix://%s/path/to/page' % urlencoded_usock
                r = requests.get(url)
"""
logger = ...
class KillThread(threading.Thread):
    def __init__(self, server, *args, **kwargs) -> None:
        ...
    
    def run(self): # -> None:
        ...
    


class WSGIApp:
    server = ...
    def __call__(self, environ, start_response): # -> list[bytes]:
        ...
    


class UnixSocketServerThread(threading.Thread):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def get_tempfile_name(self): # -> str:
        ...
    
    def run(self): # -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    


