from ._feature_set import FeatureSet as FeatureSet
from solas_shared import CONFIG as CONFIG, app_api as app_api
from solas_shared.exceptions import LicenseInvalidError as LicenseInvalidError, LicenseMissingFeatureError as LicenseMissingFeatureError
from solas_shared.types import SolasLicense as SolasLicense

def get_license() -> SolasLicense: ...
def set_license(license: str) -> SolasLicense: ...
def requires_license(features: list[str] | None = None): ...
def has_commercial() -> bool: ...
