# coding: utf-8

"""
    File Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_files.models.file_controller_put_object200_response import FileControllerPutObject200Response

class TestFileControllerPutObject200Response(unittest.TestCase):
    """FileControllerPutObject200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileControllerPutObject200Response:
        """Test FileControllerPutObject200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileControllerPutObject200Response`
        """
        model = FileControllerPutObject200Response()
        if include_optional:
            return FileControllerPutObject200Response(
                e_tag = '',
                s3 = do_sdk_files.models.file_controller_put_object_200_response_s3.FileController_putObject_200_response_s3(
                    bucket_name = '', 
                    bucket_key = '', 
                    bucket_region = '', )
            )
        else:
            return FileControllerPutObject200Response(
        )
        """

    def testFileControllerPutObject200Response(self):
        """Test FileControllerPutObject200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
