# coding: utf-8

"""
    File Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_files.models.shared_data_controller_get_do_object200_response_one_of import SharedDataControllerGetDoObject200ResponseOneOf

class TestSharedDataControllerGetDoObject200ResponseOneOf(unittest.TestCase):
    """SharedDataControllerGetDoObject200ResponseOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SharedDataControllerGetDoObject200ResponseOneOf:
        """Test SharedDataControllerGetDoObject200ResponseOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SharedDataControllerGetDoObject200ResponseOneOf`
        """
        model = SharedDataControllerGetDoObject200ResponseOneOf()
        if include_optional:
            return SharedDataControllerGetDoObject200ResponseOneOf(
                data = [
                    None
                    ],
                continuation_token = ''
            )
        else:
            return SharedDataControllerGetDoObject200ResponseOneOf(
        )
        """

    def testSharedDataControllerGetDoObject200ResponseOneOf(self):
        """Test SharedDataControllerGetDoObject200ResponseOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
