# This file was auto-generated by Fern from our API Definition.

from .....core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .saa_s_discovery_finding import SaaSDiscoveryFinding
from .....core.pydantic_utilities import IS_PYDANTIC_V2


class SaasDiscoveryRequest(UniversalBaseModel):
    url: str
    redirect_chain: typing.Optional[typing.List[str]] = pydantic.Field(alias="redirectChain", default=None)
    status_code: typing.Optional[int] = pydantic.Field(alias="statusCode", default=None)
    response_headers: typing.Optional[typing.Dict[str, str]] = pydantic.Field(alias="responseHeaders", default=None)
    response_body: typing.Optional[str] = pydantic.Field(alias="responseBody", default=None)
    findings: typing.Optional[SaaSDiscoveryFinding] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
