"""
This type stub file was generated by pyright.
"""

from pandas.compat import pa_version_under10p1

if not pa_version_under10p1:
    ...
class ArrowStringArrayMixin:
    _pa_array = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


