from pathlib import Path
from plotly.graph_objects import Figure as Figure
from solas_shared._ui import Ui as Ui
from typing import Dict, Union

class Content(Dict[str, str]):
    def __init__(self, *args, **kwargs) -> None: ...
    def __getitem__(self, key: str) -> str: ...
    def load_dir(self, path: Union[str, Path]) -> None: ...
    def load_file(self, path: Union[str, Path]) -> None: ...
    def add_plot_as_embedded(self, key: str, plot: Figure) -> None: ...
    def add_plot_as_local_path(self, key: str, plot: Figure) -> None: ...
    def plot_to_local_path(self, plot: Figure, format: str = ...) -> str: ...
    def plot_to_embedded_img(self, plot: Figure, format: str = ...) -> str: ...
