# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.filter_response_metadata_entities_entity_list_item_dto import FilterResponseMetadataEntitiesEntityListItemDto  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestFilterResponseMetadataEntitiesEntityListItemDto(unittest.TestCase):
    """FilterResponseMetadataEntitiesEntityListItemDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterResponseMetadataEntitiesEntityListItemDto(self):
        """Test FilterResponseMetadataEntitiesEntityListItemDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.filter_response_metadata_entities_entity_list_item_dto.FilterResponseMetadataEntitiesEntityListItemDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
