# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.permissions_permission_grant_request_dto_request_data_identity_access_permission import PermissionsPermissionGrantRequestDtoRequestDataIdentityAccessPermission  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestPermissionsPermissionGrantRequestDtoRequestDataIdentityAccessPermission(unittest.TestCase):
    """PermissionsPermissionGrantRequestDtoRequestDataIdentityAccessPermission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPermissionsPermissionGrantRequestDtoRequestDataIdentityAccessPermission(self):
        """Test PermissionsPermissionGrantRequestDtoRequestDataIdentityAccessPermission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.permissions_permission_grant_request_dto_request_data_identity_access_permission.PermissionsPermissionGrantRequestDtoRequestDataIdentityAccessPermission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
