# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.api_external_llagar_installation_models_installation_version_response import APIExternalLlagarInstallationModelsInstallationVersionResponse  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestAPIExternalLlagarInstallationModelsInstallationVersionResponse(unittest.TestCase):
    """APIExternalLlagarInstallationModelsInstallationVersionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAPIExternalLlagarInstallationModelsInstallationVersionResponse(self):
        """Test APIExternalLlagarInstallationModelsInstallationVersionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.api_external_llagar_installation_models_installation_version_response.APIExternalLlagarInstallationModelsInstallationVersionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
