# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.data_factory_pipelines_pipeline_upsert_definition_request import DataFactoryPipelinesPipelineUpsertDefinitionRequest  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestDataFactoryPipelinesPipelineUpsertDefinitionRequest(unittest.TestCase):
    """DataFactoryPipelinesPipelineUpsertDefinitionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataFactoryPipelinesPipelineUpsertDefinitionRequest(self):
        """Test DataFactoryPipelinesPipelineUpsertDefinitionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.data_factory_pipelines_pipeline_upsert_definition_request.DataFactoryPipelinesPipelineUpsertDefinitionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
