# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.microsoft_azure_search_models_data_type import MicrosoftAzureSearchModelsDataType  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestMicrosoftAzureSearchModelsDataType(unittest.TestCase):
    """MicrosoftAzureSearchModelsDataType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMicrosoftAzureSearchModelsDataType(self):
        """Test MicrosoftAzureSearchModelsDataType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.microsoft_azure_search_models_data_type.MicrosoftAzureSearchModelsDataType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
