# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.microsoft_azure_management_resource_manager_models_resource_group import MicrosoftAzureManagementResourceManagerModelsResourceGroup  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestMicrosoftAzureManagementResourceManagerModelsResourceGroup(unittest.TestCase):
    """MicrosoftAzureManagementResourceManagerModelsResourceGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMicrosoftAzureManagementResourceManagerModelsResourceGroup(self):
        """Test MicrosoftAzureManagementResourceManagerModelsResourceGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.microsoft_azure_management_resource_manager_models_resource_group.MicrosoftAzureManagementResourceManagerModelsResourceGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
