# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.api_data_ingestion_model_add_storage_account_request import APIDataIngestionModelAddStorageAccountRequest  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestAPIDataIngestionModelAddStorageAccountRequest(unittest.TestCase):
    """APIDataIngestionModelAddStorageAccountRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAPIDataIngestionModelAddStorageAccountRequest(self):
        """Test APIDataIngestionModelAddStorageAccountRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.api_data_ingestion_model_add_storage_account_request.APIDataIngestionModelAddStorageAccountRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
