# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.filter_response_data_factory_pipelines_pipeline_full_dto import FilterResponseDataFactoryPipelinesPipelineFullDTO  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestFilterResponseDataFactoryPipelinesPipelineFullDTO(unittest.TestCase):
    """FilterResponseDataFactoryPipelinesPipelineFullDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterResponseDataFactoryPipelinesPipelineFullDTO(self):
        """Test FilterResponseDataFactoryPipelinesPipelineFullDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.filter_response_data_factory_pipelines_pipeline_full_dto.FilterResponseDataFactoryPipelinesPipelineFullDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
