# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.api.metadata_pipeline_load_restriction_objects_pipeline_load_restriction_object_api import MetadataPipelineLoadRestrictionObjectsPipelineLoadRestrictionObjectApi  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestMetadataPipelineLoadRestrictionObjectsPipelineLoadRestrictionObjectApi(unittest.TestCase):
    """MetadataPipelineLoadRestrictionObjectsPipelineLoadRestrictionObjectApi unit test stubs"""

    def setUp(self):
        self.api = MetadataPipelineLoadRestrictionObjectsPipelineLoadRestrictionObjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_metadata_pipeline_load_restriction_object_delete_pipeline_restriction_id_delete(self):
        """Test case for api_metadata_pipeline_load_restriction_object_delete_pipeline_restriction_id_delete

        """
        pass

    def test_api_metadata_pipeline_load_restriction_object_id_delete(self):
        """Test case for api_metadata_pipeline_load_restriction_object_id_delete

        """
        pass

    def test_api_metadata_pipeline_load_restriction_object_pipeline_id_get(self):
        """Test case for api_metadata_pipeline_load_restriction_object_pipeline_id_get

        """
        pass

    def test_api_metadata_pipeline_load_restriction_object_post(self):
        """Test case for api_metadata_pipeline_load_restriction_object_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
