# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.metadata_entities_entities_with_tags_and_size_dto import MetadataEntitiesEntitiesWithTagsAndSizeDto  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestMetadataEntitiesEntitiesWithTagsAndSizeDto(unittest.TestCase):
    """MetadataEntitiesEntitiesWithTagsAndSizeDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataEntitiesEntitiesWithTagsAndSizeDto(self):
        """Test MetadataEntitiesEntitiesWithTagsAndSizeDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.metadata_entities_entities_with_tags_and_size_dto.MetadataEntitiesEntitiesWithTagsAndSizeDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
