# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.metadata_attributes_attributes_basic_with_popularities_dto import MetadataAttributesAttributesBasicWithPopularitiesDto  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestMetadataAttributesAttributesBasicWithPopularitiesDto(unittest.TestCase):
    """MetadataAttributesAttributesBasicWithPopularitiesDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataAttributesAttributesBasicWithPopularitiesDto(self):
        """Test MetadataAttributesAttributesBasicWithPopularitiesDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.metadata_attributes_attributes_basic_with_popularities_dto.MetadataAttributesAttributesBasicWithPopularitiesDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
