# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.api.databricks_jobs_jobs_api import DatabricksJobsJobsApi  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestDatabricksJobsJobsApi(unittest.TestCase):
    """DatabricksJobsJobsApi unit test stubs"""

    def setUp(self):
        self.api = DatabricksJobsJobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_databricks_jobs_id_delete(self):
        """Test case for api_databricks_jobs_id_delete

        """
        pass

    def test_api_databricks_jobs_id_get(self):
        """Test case for api_databricks_jobs_id_get

        """
        pass

    def test_api_databricks_jobs_item_id_post(self):
        """Test case for api_databricks_jobs_item_id_post

        """
        pass

    def test_api_databricks_jobs_put(self):
        """Test case for api_databricks_jobs_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
