# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.data_ingestion_storage_role import DataIngestionStorageRole  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestDataIngestionStorageRole(unittest.TestCase):
    """DataIngestionStorageRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataIngestionStorageRole(self):
        """Test DataIngestionStorageRole"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.data_ingestion_storage_role.DataIngestionStorageRole()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
