# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.pii_models_asset_for_pii_dto import PIIModelsAssetForPIIDto  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestPIIModelsAssetForPIIDto(unittest.TestCase):
    """PIIModelsAssetForPIIDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPIIModelsAssetForPIIDto(self):
        """Test PIIModelsAssetForPIIDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.pii_models_asset_for_pii_dto.PIIModelsAssetForPIIDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
