# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.metadata_assets_asset_full_dto import MetadataAssetsAssetFullDTO  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestMetadataAssetsAssetFullDTO(unittest.TestCase):
    """MetadataAssetsAssetFullDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataAssetsAssetFullDTO(self):
        """Test MetadataAssetsAssetFullDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.metadata_assets_asset_full_dto.MetadataAssetsAssetFullDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
