# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/iec61970/base/wires/generation/production/BatteryStateKind.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nTzepben/protobuf/cim/iec61970/base/wires/generation/production/BatteryStateKind.proto\x12=zepben.protobuf.cim.iec61970.base.wires.generation.production*`\n\x10\x42\x61tteryStateKind\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0b\x64ischarging\x10\x01\x12\x08\n\x04\x66ull\x10\x02\x12\x0b\n\x07waiting\x10\x03\x12\x0c\n\x08\x63harging\x10\x04\x12\t\n\x05\x65mpty\x10\x05\x42\x85\x01\nAcom.zepben.protobuf.cim.iec61970.base.wires.generation.productionP\x01\xaa\x02=Zepben.Protobuf.CIM.IEC61970.Base.Wires.Generation.Productionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zepben.protobuf.cim.iec61970.base.wires.generation.production.BatteryStateKind_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nAcom.zepben.protobuf.cim.iec61970.base.wires.generation.productionP\001\252\002=Zepben.Protobuf.CIM.IEC61970.Base.Wires.Generation.Production'
  _globals['_BATTERYSTATEKIND']._serialized_start=151
  _globals['_BATTERYSTATEKIND']._serialized_end=247
# @@protoc_insertion_point(module_scope)
