HOST_KEY = "TEMA_AI_HOST"
CLIENT_ID_KEY = "TEMA_AI_CLIENT_ID"
CLIENT_SECRET_KEY = "TEMA_AI_CLIENT_SECRET"
CONNECTION_KEY = "TEMA_AI_CONNECTION"

CREDENTIALS_API_SUBPATH = "credentials"
ACTIVATION_API_SUBPATH = "activate"
