# Generated by ariadne-codegen
# Source: ./_concatened.gql

from pydantic import Field

from .base_model import BaseModel
from .fragments import CredentialFields


class CredentialCreate(BaseModel):
    credential_create: "CredentialCreateCredentialCreate" = Field(
        alias="credentialCreate"
    )


class CredentialCreateCredentialCreate(CredentialFields):
    pass


CredentialCreate.model_rebuild()
