# This file was auto-generated by Fern from our API Definition.

from .....core.pydantic_utilities import UniversalBaseModel
import typing
from .address_fingerprint_target_info import AddressFingerprintTargetInfo
from .address_fingerprint_config import AddressFingerprintConfig
from .....core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class AddressFingerprintReport(UniversalBaseModel):
    targets: typing.List[AddressFingerprintTargetInfo]
    config: AddressFingerprintConfig
    errors: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
