---
bibliography: technical/references.bib
sidebar: main
---
::: {.text-center}
## Welcome to pySLAMMER's documentation
:::
pySLAMMER (**Py**thon package for **S**eismic **L**andslide **M**ovement **M**odeled using **E**arthquake **R**ecords) is tool for estimating the co-seismic displacements of landslides with rigid and flexible sliding-block analyses. The package name and code are based on the USGS tool [SLAMMER](https://pubs.usgs.gov/tm/12b1/) by @jibson2013.

pySLAMMER includes the same sliding block analysis methods ([rigid](api/RigidAnalysis.qmd), [decoupled](api/Decoupled.qmd), and [coupled](api/Coupled.qmd)) as SLAMMER. See the verifications section for [a comparison of results between pySLAMMER and the original SLAMMER](technical/comp_SLAMMER_results.qmd).


::: {.text-center}
## Site Contents
:::

::: {.grid}

::: {.g-col-4 .card}
::: {.card-body}
[Get Started](quickstart.qmd){.btn .w-100}

Want to try pySLAMMER?
Get started with the quickstart guide.
:::
:::

::: {.g-col-4 .card}
::: {.card-body}
[Examples](examples/index.qmd){.btn .w-100}

See the different sliding block models compared and batches of analyses.
:::
:::

::: {.g-col-4 .card}
::: {.card-body}
[API Reference](api/index.qmd){.btn .w-100}

Look into pySLAMMER's classes and functions.
:::
:::

::: {.g-col-4 .card}
::: {.card-body}
[Technical manual](technical/tech_manual.qmd){.btn .w-100}

Definitions of key terms, background, and model verification.
:::
:::

::: {.g-col-4 .card}
::: {.card-body}
[Develop](about/develop.qmd){.btn .w-100}

Have your own sliding block model you'd like to add? 
Community contributions are welcome!
:::
:::

::: {.g-col-4 .card}
::: {.card-body}
[About](about/motivation.qmd){.btn .w-100}

Why does pySLAMMER exist?
What's next?
:::
:::

:::



<!-- 
See the [roadmap] for additional models we plan to add. 
Have your own sliding block model you'd like to add? Community [contributions] are welcome!

Welcome
Technical stuff
Verifications
Invitation to contribute
Roadmap

## Contents

[Quickstart guide](quickstart.qmd)

[Examples](examples.qmd)

[API Reference](api/index.qmd)

[Verification](verifications/verification.qmd) -->