/* tslint:disable */
/* eslint-disable */
/**
 * elkar-app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IsRegisteredOutput
 */
export interface IsRegisteredOutput {
    /**
     * 
     * @type {boolean}
     * @memberof IsRegisteredOutput
     */
    isRegistered: boolean;
}

/**
 * Check if a given object implements the IsRegisteredOutput interface.
 */
export function instanceOfIsRegisteredOutput(value: object): value is IsRegisteredOutput {
    if (!('isRegistered' in value) || value['isRegistered'] === undefined) return false;
    return true;
}

export function IsRegisteredOutputFromJSON(json: any): IsRegisteredOutput {
    return IsRegisteredOutputFromJSONTyped(json, false);
}

export function IsRegisteredOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsRegisteredOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'isRegistered': json['is_registered'],
    };
}

export function IsRegisteredOutputToJSON(json: any): IsRegisteredOutput {
    return IsRegisteredOutputToJSONTyped(json, false);
}

export function IsRegisteredOutputToJSONTyped(value?: IsRegisteredOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_registered': value['isRegistered'],
    };
}

