# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.exchange_token_request import ExchangeTokenRequest


class TestExchangeTokenRequest(unittest.TestCase):
    """ExchangeTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExchangeTokenRequest:
        """Test ExchangeTokenRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ExchangeTokenRequest`
        """
        model = ExchangeTokenRequest()
        if include_optional:
            return ExchangeTokenRequest(
                exchangeable_token = ''
            )
        else:
            return ExchangeTokenRequest(
                exchangeable_token = '',
        )
        """

    def testExchangeTokenRequest(self):
        """Test ExchangeTokenRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
