# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.api_error_auth_expired_access_token_response import (
    APIErrorAuthExpiredAccessTokenResponse,
)


class TestAPIErrorAuthExpiredAccessTokenResponse(unittest.TestCase):
    """APIErrorAuthExpiredAccessTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIErrorAuthExpiredAccessTokenResponse:
        """Test APIErrorAuthExpiredAccessTokenResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `APIErrorAuthExpiredAccessTokenResponse`
        """
        model = APIErrorAuthExpiredAccessTokenResponse()
        if include_optional:
            return APIErrorAuthExpiredAccessTokenResponse(
                error_code = 'api_error.auth.expired_access_token',
                error_message = 'Access token expired',
                documentation_url = ''
            )
        else:
            return APIErrorAuthExpiredAccessTokenResponse(
        )
        """

    def testAPIErrorAuthExpiredAccessTokenResponse(self):
        """Test APIErrorAuthExpiredAccessTokenResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
