# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.phone_number import PhoneNumber


class TestPhoneNumber(unittest.TestCase):
    """PhoneNumber unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PhoneNumber:
        """Test PhoneNumber
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PhoneNumber`
        """
        model = PhoneNumber()
        if include_optional:
            return PhoneNumber(
                number = '',
                primary = True,
                type = 'home'
            )
        else:
            return PhoneNumber(
                number = '',
                type = 'home',
        )
        """

    def testPhoneNumber(self):
        """Test PhoneNumber"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
