# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.api_error_auth_unauthorized_response import (
    APIErrorAuthUnauthorizedResponse,
)


class TestAPIErrorAuthUnauthorizedResponse(unittest.TestCase):
    """APIErrorAuthUnauthorizedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIErrorAuthUnauthorizedResponse:
        """Test APIErrorAuthUnauthorizedResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `APIErrorAuthUnauthorizedResponse`
        """
        model = APIErrorAuthUnauthorizedResponse()
        if include_optional:
            return APIErrorAuthUnauthorizedResponse(
                error_code = 'api_error.auth.unauthorized',
                error_message = '',
                documentation_url = ''
            )
        else:
            return APIErrorAuthUnauthorizedResponse(
                error_message = '',
        )
        """

    def testAPIErrorAuthUnauthorizedResponse(self):
        """Test APIErrorAuthUnauthorizedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
