# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.bacs_number import BacsNumber


class TestBacsNumber(unittest.TestCase):
    """BacsNumber unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BacsNumber:
        """Test BacsNumber
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BacsNumber`
        """
        model = BacsNumber()
        if include_optional:
            return BacsNumber(
                account_number = '',
                sort_code = ''
            )
        else:
            return BacsNumber(
                account_number = '',
                sort_code = '',
        )
        """

    def testBacsNumber(self):
        """Test BacsNumber"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
