# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.response401_get_transactions_sync_links_id_transactions_sync_get import (
    Response401GetTransactionsSyncLinksIdTransactionsSyncGet,
)


class TestResponse401GetTransactionsSyncLinksIdTransactionsSyncGet(unittest.TestCase):
    """Response401GetTransactionsSyncLinksIdTransactionsSyncGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> Response401GetTransactionsSyncLinksIdTransactionsSyncGet:
        """Test Response401GetTransactionsSyncLinksIdTransactionsSyncGet
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Response401GetTransactionsSyncLinksIdTransactionsSyncGet`
        """
        model = Response401GetTransactionsSyncLinksIdTransactionsSyncGet()
        if include_optional:
            return Response401GetTransactionsSyncLinksIdTransactionsSyncGet(
                error_code = link_error.unauthorized_access,
                error_message = None,
                documentation_url = None
            )
        else:
            return Response401GetTransactionsSyncLinksIdTransactionsSyncGet(
                error_message = None,
        )
        """

    def testResponse401GetTransactionsSyncLinksIdTransactionsSyncGet(self):
        """Test Response401GetTransactionsSyncLinksIdTransactionsSyncGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
