# coding: utf-8

"""
MoneyKit API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-02-18
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from moneykit.models.response401_trigger_test_link_webhook_event_webhooks_test_link_id_post import (
    Response401TriggerTestLinkWebhookEventWebhooksTestLinkIdPost,
)


class TestResponse401TriggerTestLinkWebhookEventWebhooksTestLinkIdPost(
    unittest.TestCase
):
    """Response401TriggerTestLinkWebhookEventWebhooksTestLinkIdPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> Response401TriggerTestLinkWebhookEventWebhooksTestLinkIdPost:
        """Test Response401TriggerTestLinkWebhookEventWebhooksTestLinkIdPost
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Response401TriggerTestLinkWebhookEventWebhooksTestLinkIdPost`
        """
        model = Response401TriggerTestLinkWebhookEventWebhooksTestLinkIdPost()
        if include_optional:
            return Response401TriggerTestLinkWebhookEventWebhooksTestLinkIdPost(
                error_code = link_error.unauthorized_access,
                error_message = None,
                documentation_url = None
            )
        else:
            return Response401TriggerTestLinkWebhookEventWebhooksTestLinkIdPost(
                error_message = None,
        )
        """

    def testResponse401TriggerTestLinkWebhookEventWebhooksTestLinkIdPost(self):
        """Test Response401TriggerTestLinkWebhookEventWebhooksTestLinkIdPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
