"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class WorkflowInputFieldTypedDict(TypedDict):
    name: NotRequired[str]
    r"""The name of the input."""


class WorkflowInputField(BaseModel):
    name: Optional[str] = None
    r"""The name of the input."""
