# Autogenerated by devscripts/update-version.py

__version__ = '2025.05.06.232932'

RELEASE_GIT_HEAD = 'b26bc32579c00ef579d75a835807ccc87d20ee0a'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2025.05.06.232932dev'
