from ._enum_base import EnumBase as EnumBase

class DisparityCalculation(EnumBase):
    ADVERSE_IMPACT_RATIO: str
    RELATIVE_RATE: str
    SEGMENTED_ADVERSE_IMPACT_RATIO: str
    ADVERSE_IMPACT_RATIO_BY_QUANTILE: str
    CATEGORICAL_ADVERSE_IMPACT_RATIO: str
    STANDARDIZED_MEAN_DIFFERENCE: str
    RESIDUAL_STANDARDIZED_MEAN_DIFFERENCE: str
    ODDS_RATIO: str
    CUSTOM_DISPARITY_METRIC: str
    TRUE_POSITIVE_RATE: str
    TRUE_NEGATIVE_RATE: str
    FALSE_POSITIVE_RATE: str
    FALSE_NEGATIVE_RATE: str
    PRECISION: str
    FALSE_DISCOVERY_RATE: str
    SCORING_IMPACT_RATIO: str
    SELECTION_IMPACT_RATIO: str
    NOT_SET: str
