DEFAULT_CONTROLLER_PORT = 38000
DEFAULT_CONTROLLER_HOST = 'localhost'
BASE_PATH = "/api/v1"
INFO_NUT_PATH = f"{BASE_PATH}/infoNUT"
RUN_NUT_PATH = f"{BASE_PATH}/runNUT"
STOP_NUT_PATH = f"{BASE_PATH}/stopNUT"
TEST_RESULTS = f"{BASE_PATH}/testResults"
NEW_ACTION = f"{BASE_PATH}/newAction"
