# coding: utf-8

"""
    Automated Optical Inspection API

    AOI_API   # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: corey.sadler@3adesign.co.uk
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import AOI_API
from AOI_API.api.aoi_api import AOIApi  # noqa: E501
from AOI_API.rest import ApiException


class TestAOIApi(unittest.TestCase):
    """AOIApi unit test stubs"""

    def setUp(self):
        self.api = AOI_API.api.aoi_api.AOIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_scan_board(self):
        """Test case for post_scan_board

          # noqa: E501
        """
        pass

    def test_put_calibration(self):
        """Test case for put_calibration

          # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
