# Generated by ariadne-codegen
# Source: ./_concatened.gql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import ServiceDetailsFragment


class SaasFind(BaseModel):
    saas_find: Optional["SaasFindSaasFind"] = Field(alias="saasFind")


class SaasFindSaasFind(BaseModel):
    cid: str
    dev: Optional[str]
    list: List["SaasFindSaasFindList"]
    stable: Optional[str]


class SaasFindSaasFindList(ServiceDetailsFragment):
    pass


SaasFind.model_rebuild()
SaasFindSaasFind.model_rebuild()
