# Generated by ariadne-codegen
# Source: ./_concatened.gql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import TopologyVersionFields


class TopologyVersionGet(BaseModel):
    topology_version_get: Optional["TopologyVersionGetTopologyVersionGet"] = Field(
        alias="topologyVersionGet"
    )


class TopologyVersionGetTopologyVersionGet(TopologyVersionFields):
    pass


TopologyVersionGet.model_rebuild()
