# -*- coding: utf-8 -*-

# fmt: off
from .utils import role_name_to_inline_policy_name
from .service_principal_enum import ServicePrincipalEnum
from .policy_statement import create_get_caller_identity_statement
from .policy_statement import create_assume_role_statement
from .policy_statement import create_allow_all_services_except_identity_management_statement
from .policy_statement import create_account_and_org_and_iam_read_only_statement
from .policy_statement import create_prefixed_iam_management_statement
from .policy_statement import create_require_permission_boundary_for_role_creation_statement
from .policy_statement import create_restricted_read_only_statement
from .policy_document import create_get_caller_identity_document
from .policy_document import create_assume_role_document
from .policy_document import create_power_ops_document
from .policy_document import create_restricted_read_only_document
from .github_oidc import create_github_oidc_provider
from .github_oidc import GITHUB_OIDC_PROVIDER_ARN
from .github_oidc import create_github_repo_main_iam_role_assumed_by
from .github_oidc import GitHubOidcProviderParams
from .github_oidc import GitHubOidcProvider
from .github_oidc import GitHubOidcSingleAccountParams
from .github_oidc import GitHubOidcSingleAccount
from .github_oidc import GitHubOidcMultiAccountDevopsParams
from .github_oidc import GitHubOidcMultiAccountDevops
from .github_oidc import GitHubOidcMultiAccountWorkloadParams
from .github_oidc import GitHubOidcMultiAccountWorkload
# fmt: on
