import pandas as pd
from _typeshed import Incomplete
from solas_disparity import const as const
from solas_shared import Ui as _SharedUi
from typing import Any, Callable, Dict, Optional, Union

class Ui(_SharedUi):
    AUTO_FORMATTERS: Incomplete
    def __init__(self) -> None: ...
    def autoformatter(self) -> Dict[str, Callable]: ...
    def df_to_html_defaults(self, table: pd.DataFrame, is_notebook: Optional[bool] = ...) -> dict: ...
    def show(self, obj: Union[pd.DataFrame, Any], auto_format: bool = ...) -> None: ...
