# Generated by Django 5.1.7 on 2025-03-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0013_host_is_ephemeral_template_ephemeral_peers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Same as group but accepts multiple values. Multiple values are AND'd together and a certificate must contain all groups to pass.",
                related_name="fw_groupss",
                to="networks.group",
            ),
        ),
    ]
