# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .links import LinksParams
from .meta import MetaParams


class ApiResponseBaseParams(typing_extensions.TypedDict):
    """
    Base structure for standard API responses.
    """

    meta: typing_extensions.NotRequired[MetaParams]
    links: typing_extensions.NotRequired[LinksParams]
