# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .links import LinksParams
from .meta import MetaParams
from .task import TaskParams


class TaskResponseParams(typing_extensions.TypedDict):
    """
    Standard wrapper for single Task responses.
    """

    meta: typing_extensions.NotRequired[MetaParams]
    data: typing_extensions.NotRequired[TaskParams]
    links: typing_extensions.NotRequired[LinksParams]
