import uvicorn
from ._auth_static_files import AuthStaticFiles as AuthStaticFiles
from _typeshed import Incomplete
from collections.abc import Generator
from fastapi import FastAPI as FastAPI
from solas_shared._config import Config as Config

class App(uvicorn.Server):
    solas_config: Incomplete
    api: Incomplete
    def __init__(self, api: FastAPI, config: Config) -> None: ...
    def install_signal_handlers(self) -> None: ...
    def root_url(self) -> str: ...
    should_exit: bool
    def run_in_thread(self) -> Generator[None]: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
