from fastapi import Request as Request
from solas_shared import app_api as app_api
from solas_shared._app._auth_static_files import verify_username as verify_username
from solas_shared.types import get_name_slug as get_name_slug, get_new_id as get_new_id

async def value_error_exception_handler(request: Request, exc: ValueError): ...
async def app_redirect(): ...
async def say_hello(name: str = 'World'): ...
def get_current_user(username: str = ...): ...
