# Generated by ariadne-codegen
# Source: ./_concatened.gql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import InstanceDetails


class InstancesList(BaseModel):
    instances_list: Optional[List["InstancesListInstancesList"]] = Field(
        alias="instancesList"
    )


class InstancesListInstancesList(InstanceDetails):
    pass


InstancesList.model_rebuild()
