# Generated by ariadne-codegen
# Source: ./_concatened.gql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import WsMappingDetails


class MappingGet(BaseModel):
    mapping_get: Optional["MappingGetMappingGet"] = Field(alias="mappingGet")


class MappingGetMappingGet(WsMappingDetails):
    pass


MappingGet.model_rebuild()
