# Generated by ariadne-codegen
# Source: ./_concatened.gql

from typing import List

from pydantic import Field

from .base_model import BaseModel


class UserActivity(BaseModel):
    user_activity: List["UserActivityUserActivity"] = Field(alias="userActivity")


class UserActivityUserActivity(BaseModel):
    dn: str
    name: str
    ws_act: List["UserActivityUserActivityWsAct"] = Field(alias="wsAct")


class UserActivityUserActivityWsAct(BaseModel):
    id: str
    last_con: int = Field(alias="lastCon")


UserActivity.model_rebuild()
UserActivityUserActivity.model_rebuild()
