# generated by datamodel-codegen:
#   filename:  geojsonsource.json
#   timestamp: 2025-05-08T01:23:34+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from . import geojson


class IGeoJSONSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: Optional[str] = Field(None, description='The local path to a GeoJSON file')
    data: Optional[geojson.GeoJSON] = Field(None, description='The GeoJSON data')
    valid: Optional[bool] = Field(None, description='Whether the data are valid or not')
