#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2501-43-ga9e8f2a1"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2501
#define NETGEN_VERSION_TWEAK 43
#define NETGEN_VERSION_HASH "ga9e8f2a1"
#endif // NETGEN_VERSION_HPP_INCLUDED
