"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "apideck-unify"
__version__: str = "0.14.0"
__openapi_doc_version__: str = "10.16.5"
__gen_version__: str = "2.597.9"
__user_agent__: str = "speakeasy-sdk/python 0.14.0 2.597.9 10.16.5 apideck-unify"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
