
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-07T14:03:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e01cdf433fc1defa6010f86549a63f56502797b",
 "version": "2025.5.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
