class RepositoryCreationException(Exception): ...


class RepositoryDeletionException(Exception): ...


class NamespaceException(Exception): ...


class RepositoryNotFoundException(Exception): ...


class RepositoryInternalException(Exception): ...
