
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-07T09:17:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "024c93d76b2de1df79745aca9c185ec0ea9395e6",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
