# Generated by Django 5.1.7 on 2025-03-08 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0011_ca_created_at_ca_updated_at_firewall_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="config_freeze",
            field=models.BooleanField(
                default=False,
                help_text="When true, host will not receive automatic config updates",
            ),
        ),
        migrations.CreateModel(
            name="ConfigRollout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "completed_hosts",
                    models.ManyToManyField(
                        related_name="completed_rollouts", to="networks.host"
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="networks.network",
                    ),
                ),
                (
                    "target_hosts",
                    models.ManyToManyField(
                        related_name="pending_rollouts", to="networks.host"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
