# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyst_client.api.concept_scheme_api import ConceptSchemeApi


class TestConceptSchemeApi(unittest.IsolatedAsyncioTestCase):
    """ConceptSchemeApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ConceptSchemeApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_concept_scheme_create_concept_scheme_post(self) -> None:
        """Test case for concept_scheme_create_concept_scheme_post

        Create a `ConceptScheme` object
        """
        pass

    async def test_concept_scheme_delete_concept_scheme_delete(self) -> None:
        """Test case for concept_scheme_delete_concept_scheme_delete

        Delete a `ConceptScheme` object
        """
        pass

    async def test_concept_scheme_get_concept_scheme_get(self) -> None:
        """Test case for concept_scheme_get_concept_scheme_get

        Get a `ConceptScheme` object
        """
        pass

    async def test_concept_scheme_update_concept_scheme_put(self) -> None:
        """Test case for concept_scheme_update_concept_scheme_put

        Update a `ConceptScheme` object
        """
        pass


if __name__ == '__main__':
    unittest.main()
