# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyst_client.models.date_time_type import DateTimeType

class TestDateTimeType(unittest.TestCase):
    """DateTimeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDateTimeType(self):
        """Test DateTimeType"""
        # inst = DateTimeType()

if __name__ == '__main__':
    unittest.main()
