
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-10T14:12:35+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4c4987760e72ac7789c0b82956155b28ab3fc89",
 "version": "0.49"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
