
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-07T12:56:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c726453a6aef7fd9f7891624532edf56514d822c",
 "version": "2025.5.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
