# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'id_activity_template': 'int',
        'id_pipeline_template': 'int',
        'order': 'int',
        'parameters': 'str',
        'item_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'id_activity_template': 'idActivityTemplate',
        'id_pipeline_template': 'idPipelineTemplate',
        'order': 'order',
        'parameters': 'parameters',
        'item_id': 'itemId'
    }

    def __init__(self, id=None, id_activity_template=None, id_pipeline_template=None, order=None, parameters=None, item_id=None):  # noqa: E501
        """DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._id_activity_template = None
        self._id_pipeline_template = None
        self._order = None
        self._parameters = None
        self._item_id = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if id_activity_template is not None:
            self.id_activity_template = id_activity_template
        if id_pipeline_template is not None:
            self.id_pipeline_template = id_pipeline_template
        if order is not None:
            self.order = order
        if parameters is not None:
            self.parameters = parameters
        if item_id is not None:
            self.item_id = item_id

    @property
    def id(self):
        """Gets the id of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501


        :return: The id of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.


        :param id: The id of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def id_activity_template(self):
        """Gets the id_activity_template of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501


        :return: The id_activity_template of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501
        :rtype: int
        """
        return self._id_activity_template

    @id_activity_template.setter
    def id_activity_template(self, id_activity_template):
        """Sets the id_activity_template of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.


        :param id_activity_template: The id_activity_template of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501
        :type: int
        """

        self._id_activity_template = id_activity_template

    @property
    def id_pipeline_template(self):
        """Gets the id_pipeline_template of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501


        :return: The id_pipeline_template of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501
        :rtype: int
        """
        return self._id_pipeline_template

    @id_pipeline_template.setter
    def id_pipeline_template(self, id_pipeline_template):
        """Sets the id_pipeline_template of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.


        :param id_pipeline_template: The id_pipeline_template of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501
        :type: int
        """

        self._id_pipeline_template = id_pipeline_template

    @property
    def order(self):
        """Gets the order of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501


        :return: The order of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.


        :param order: The order of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501
        :type: int
        """

        self._order = order

    @property
    def parameters(self):
        """Gets the parameters of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501


        :return: The parameters of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501
        :rtype: str
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.


        :param parameters: The parameters of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501
        :type: str
        """

        self._parameters = parameters

    @property
    def item_id(self):
        """Gets the item_id of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501


        :return: The item_id of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id):
        """Sets the item_id of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.


        :param item_id: The item_id of this DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO.  # noqa: E501
        :type: str
        """

        self._item_id = item_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataFactoryActivityTemplatesActivityTemplatePipelineTemplateDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
