# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataStorageUnitDatabricksDatabricksSecretRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data_storage_unit_id': 'int',
        'scope': 'str',
        'name': 'str',
        'value': 'str'
    }

    attribute_map = {
        'data_storage_unit_id': 'dataStorageUnitId',
        'scope': 'scope',
        'name': 'name',
        'value': 'value'
    }

    def __init__(self, data_storage_unit_id=None, scope=None, name=None, value=None):  # noqa: E501
        """DataStorageUnitDatabricksDatabricksSecretRequest - a model defined in Swagger"""  # noqa: E501
        self._data_storage_unit_id = None
        self._scope = None
        self._name = None
        self._value = None
        self.discriminator = None
        self.data_storage_unit_id = data_storage_unit_id
        self.scope = scope
        self.name = name
        self.value = value

    @property
    def data_storage_unit_id(self):
        """Gets the data_storage_unit_id of this DataStorageUnitDatabricksDatabricksSecretRequest.  # noqa: E501


        :return: The data_storage_unit_id of this DataStorageUnitDatabricksDatabricksSecretRequest.  # noqa: E501
        :rtype: int
        """
        return self._data_storage_unit_id

    @data_storage_unit_id.setter
    def data_storage_unit_id(self, data_storage_unit_id):
        """Sets the data_storage_unit_id of this DataStorageUnitDatabricksDatabricksSecretRequest.


        :param data_storage_unit_id: The data_storage_unit_id of this DataStorageUnitDatabricksDatabricksSecretRequest.  # noqa: E501
        :type: int
        """
        if data_storage_unit_id is None:
            raise ValueError("Invalid value for `data_storage_unit_id`, must not be `None`")  # noqa: E501

        self._data_storage_unit_id = data_storage_unit_id

    @property
    def scope(self):
        """Gets the scope of this DataStorageUnitDatabricksDatabricksSecretRequest.  # noqa: E501


        :return: The scope of this DataStorageUnitDatabricksDatabricksSecretRequest.  # noqa: E501
        :rtype: str
        """
        return self._scope

    @scope.setter
    def scope(self, scope):
        """Sets the scope of this DataStorageUnitDatabricksDatabricksSecretRequest.


        :param scope: The scope of this DataStorageUnitDatabricksDatabricksSecretRequest.  # noqa: E501
        :type: str
        """
        if scope is None:
            raise ValueError("Invalid value for `scope`, must not be `None`")  # noqa: E501

        self._scope = scope

    @property
    def name(self):
        """Gets the name of this DataStorageUnitDatabricksDatabricksSecretRequest.  # noqa: E501


        :return: The name of this DataStorageUnitDatabricksDatabricksSecretRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DataStorageUnitDatabricksDatabricksSecretRequest.


        :param name: The name of this DataStorageUnitDatabricksDatabricksSecretRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def value(self):
        """Gets the value of this DataStorageUnitDatabricksDatabricksSecretRequest.  # noqa: E501


        :return: The value of this DataStorageUnitDatabricksDatabricksSecretRequest.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this DataStorageUnitDatabricksDatabricksSecretRequest.


        :param value: The value of this DataStorageUnitDatabricksDatabricksSecretRequest.  # noqa: E501
        :type: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataStorageUnitDatabricksDatabricksSecretRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataStorageUnitDatabricksDatabricksSecretRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
