# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id_asset': 'int',
        'id_pipeline': 'int',
        'index_name': 'str',
        'id_status': 'PersistenceCommonEntitiesDataIngestionAssetStatusEnum',
        'last_updated': 'datetime',
        'asset': 'MetadataAssetIndexingStatusesAssetSimpleDTO',
        'asset_status_name': 'str',
        'knowledge_store': 'APIExternalKnowledgeStoreDto'
    }

    attribute_map = {
        'id_asset': 'idAsset',
        'id_pipeline': 'idPipeline',
        'index_name': 'indexName',
        'id_status': 'idStatus',
        'last_updated': 'lastUpdated',
        'asset': 'asset',
        'asset_status_name': 'assetStatusName',
        'knowledge_store': 'knowledgeStore'
    }

    def __init__(self, id_asset=None, id_pipeline=None, index_name=None, id_status=None, last_updated=None, asset=None, asset_status_name=None, knowledge_store=None):  # noqa: E501
        """MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO - a model defined in Swagger"""  # noqa: E501
        self._id_asset = None
        self._id_pipeline = None
        self._index_name = None
        self._id_status = None
        self._last_updated = None
        self._asset = None
        self._asset_status_name = None
        self._knowledge_store = None
        self.discriminator = None
        if id_asset is not None:
            self.id_asset = id_asset
        if id_pipeline is not None:
            self.id_pipeline = id_pipeline
        if index_name is not None:
            self.index_name = index_name
        if id_status is not None:
            self.id_status = id_status
        if last_updated is not None:
            self.last_updated = last_updated
        if asset is not None:
            self.asset = asset
        if asset_status_name is not None:
            self.asset_status_name = asset_status_name
        if knowledge_store is not None:
            self.knowledge_store = knowledge_store

    @property
    def id_asset(self):
        """Gets the id_asset of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501


        :return: The id_asset of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :rtype: int
        """
        return self._id_asset

    @id_asset.setter
    def id_asset(self, id_asset):
        """Sets the id_asset of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.


        :param id_asset: The id_asset of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :type: int
        """

        self._id_asset = id_asset

    @property
    def id_pipeline(self):
        """Gets the id_pipeline of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501


        :return: The id_pipeline of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :rtype: int
        """
        return self._id_pipeline

    @id_pipeline.setter
    def id_pipeline(self, id_pipeline):
        """Sets the id_pipeline of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.


        :param id_pipeline: The id_pipeline of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :type: int
        """

        self._id_pipeline = id_pipeline

    @property
    def index_name(self):
        """Gets the index_name of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501


        :return: The index_name of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :rtype: str
        """
        return self._index_name

    @index_name.setter
    def index_name(self, index_name):
        """Sets the index_name of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.


        :param index_name: The index_name of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :type: str
        """

        self._index_name = index_name

    @property
    def id_status(self):
        """Gets the id_status of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501


        :return: The id_status of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :rtype: PersistenceCommonEntitiesDataIngestionAssetStatusEnum
        """
        return self._id_status

    @id_status.setter
    def id_status(self, id_status):
        """Sets the id_status of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.


        :param id_status: The id_status of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :type: PersistenceCommonEntitiesDataIngestionAssetStatusEnum
        """

        self._id_status = id_status

    @property
    def last_updated(self):
        """Gets the last_updated of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501


        :return: The last_updated of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :rtype: datetime
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated):
        """Sets the last_updated of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.


        :param last_updated: The last_updated of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :type: datetime
        """

        self._last_updated = last_updated

    @property
    def asset(self):
        """Gets the asset of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501


        :return: The asset of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :rtype: MetadataAssetIndexingStatusesAssetSimpleDTO
        """
        return self._asset

    @asset.setter
    def asset(self, asset):
        """Sets the asset of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.


        :param asset: The asset of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :type: MetadataAssetIndexingStatusesAssetSimpleDTO
        """

        self._asset = asset

    @property
    def asset_status_name(self):
        """Gets the asset_status_name of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501


        :return: The asset_status_name of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :rtype: str
        """
        return self._asset_status_name

    @asset_status_name.setter
    def asset_status_name(self, asset_status_name):
        """Sets the asset_status_name of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.


        :param asset_status_name: The asset_status_name of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :type: str
        """

        self._asset_status_name = asset_status_name

    @property
    def knowledge_store(self):
        """Gets the knowledge_store of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501


        :return: The knowledge_store of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :rtype: APIExternalKnowledgeStoreDto
        """
        return self._knowledge_store

    @knowledge_store.setter
    def knowledge_store(self, knowledge_store):
        """Sets the knowledge_store of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.


        :param knowledge_store: The knowledge_store of this MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO.  # noqa: E501
        :type: APIExternalKnowledgeStoreDto
        """

        self._knowledge_store = knowledge_store

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetadataAssetIndexingStatusesAssetIndexingStatusFullDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
