# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_time': 'datetime',
        'changed_time': 'datetime',
        'provisioning_state': 'str',
        'plan': 'MicrosoftAzureManagementResourceManagerModelsPlan',
        'properties': 'object',
        'kind': 'str',
        'managed_by': 'str',
        'sku': 'MicrosoftAzureManagementResourceManagerModelsSku',
        'identity': 'MicrosoftAzureManagementResourceManagerModelsIdentity',
        'id': 'str',
        'name': 'str',
        'type': 'str',
        'location': 'str',
        'extended_location': 'MicrosoftAzureManagementResourceManagerModelsExtendedLocation',
        'tags': 'dict(str, str)'
    }

    attribute_map = {
        'created_time': 'createdTime',
        'changed_time': 'changedTime',
        'provisioning_state': 'provisioningState',
        'plan': 'plan',
        'properties': 'properties',
        'kind': 'kind',
        'managed_by': 'managedBy',
        'sku': 'sku',
        'identity': 'identity',
        'id': 'id',
        'name': 'name',
        'type': 'type',
        'location': 'location',
        'extended_location': 'extendedLocation',
        'tags': 'tags'
    }

    def __init__(self, created_time=None, changed_time=None, provisioning_state=None, plan=None, properties=None, kind=None, managed_by=None, sku=None, identity=None, id=None, name=None, type=None, location=None, extended_location=None, tags=None):  # noqa: E501
        """MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded - a model defined in Swagger"""  # noqa: E501
        self._created_time = None
        self._changed_time = None
        self._provisioning_state = None
        self._plan = None
        self._properties = None
        self._kind = None
        self._managed_by = None
        self._sku = None
        self._identity = None
        self._id = None
        self._name = None
        self._type = None
        self._location = None
        self._extended_location = None
        self._tags = None
        self.discriminator = None
        if created_time is not None:
            self.created_time = created_time
        if changed_time is not None:
            self.changed_time = changed_time
        if provisioning_state is not None:
            self.provisioning_state = provisioning_state
        if plan is not None:
            self.plan = plan
        if properties is not None:
            self.properties = properties
        if kind is not None:
            self.kind = kind
        if managed_by is not None:
            self.managed_by = managed_by
        if sku is not None:
            self.sku = sku
        if identity is not None:
            self.identity = identity
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if location is not None:
            self.location = location
        if extended_location is not None:
            self.extended_location = extended_location
        if tags is not None:
            self.tags = tags

    @property
    def created_time(self):
        """Gets the created_time of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The created_time of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: datetime
        """
        return self._created_time

    @created_time.setter
    def created_time(self, created_time):
        """Sets the created_time of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param created_time: The created_time of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: datetime
        """

        self._created_time = created_time

    @property
    def changed_time(self):
        """Gets the changed_time of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The changed_time of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: datetime
        """
        return self._changed_time

    @changed_time.setter
    def changed_time(self, changed_time):
        """Sets the changed_time of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param changed_time: The changed_time of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: datetime
        """

        self._changed_time = changed_time

    @property
    def provisioning_state(self):
        """Gets the provisioning_state of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The provisioning_state of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: str
        """
        return self._provisioning_state

    @provisioning_state.setter
    def provisioning_state(self, provisioning_state):
        """Sets the provisioning_state of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param provisioning_state: The provisioning_state of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: str
        """

        self._provisioning_state = provisioning_state

    @property
    def plan(self):
        """Gets the plan of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The plan of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: MicrosoftAzureManagementResourceManagerModelsPlan
        """
        return self._plan

    @plan.setter
    def plan(self, plan):
        """Sets the plan of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param plan: The plan of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: MicrosoftAzureManagementResourceManagerModelsPlan
        """

        self._plan = plan

    @property
    def properties(self):
        """Gets the properties of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The properties of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: object
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param properties: The properties of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: object
        """

        self._properties = properties

    @property
    def kind(self):
        """Gets the kind of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The kind of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param kind: The kind of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: str
        """

        self._kind = kind

    @property
    def managed_by(self):
        """Gets the managed_by of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The managed_by of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: str
        """
        return self._managed_by

    @managed_by.setter
    def managed_by(self, managed_by):
        """Sets the managed_by of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param managed_by: The managed_by of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: str
        """

        self._managed_by = managed_by

    @property
    def sku(self):
        """Gets the sku of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The sku of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: MicrosoftAzureManagementResourceManagerModelsSku
        """
        return self._sku

    @sku.setter
    def sku(self, sku):
        """Sets the sku of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param sku: The sku of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: MicrosoftAzureManagementResourceManagerModelsSku
        """

        self._sku = sku

    @property
    def identity(self):
        """Gets the identity of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The identity of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: MicrosoftAzureManagementResourceManagerModelsIdentity
        """
        return self._identity

    @identity.setter
    def identity(self, identity):
        """Sets the identity of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param identity: The identity of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: MicrosoftAzureManagementResourceManagerModelsIdentity
        """

        self._identity = identity

    @property
    def id(self):
        """Gets the id of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The id of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param id: The id of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The name of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param name: The name of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The type of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param type: The type of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def location(self):
        """Gets the location of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The location of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param location: The location of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: str
        """

        self._location = location

    @property
    def extended_location(self):
        """Gets the extended_location of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The extended_location of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: MicrosoftAzureManagementResourceManagerModelsExtendedLocation
        """
        return self._extended_location

    @extended_location.setter
    def extended_location(self, extended_location):
        """Sets the extended_location of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param extended_location: The extended_location of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: MicrosoftAzureManagementResourceManagerModelsExtendedLocation
        """

        self._extended_location = extended_location

    @property
    def tags(self):
        """Gets the tags of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501


        :return: The tags of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.


        :param tags: The tags of this MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded.  # noqa: E501
        :type: dict(str, str)
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MicrosoftAzureManagementResourceManagerModelsGenericResourceExpanded):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
