# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MicrosoftAzureManagementStorageModelsUserAssignedIdentity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'principal_id': 'str',
        'client_id': 'str'
    }

    attribute_map = {
        'principal_id': 'principalId',
        'client_id': 'clientId'
    }

    def __init__(self, principal_id=None, client_id=None):  # noqa: E501
        """MicrosoftAzureManagementStorageModelsUserAssignedIdentity - a model defined in Swagger"""  # noqa: E501
        self._principal_id = None
        self._client_id = None
        self.discriminator = None
        if principal_id is not None:
            self.principal_id = principal_id
        if client_id is not None:
            self.client_id = client_id

    @property
    def principal_id(self):
        """Gets the principal_id of this MicrosoftAzureManagementStorageModelsUserAssignedIdentity.  # noqa: E501


        :return: The principal_id of this MicrosoftAzureManagementStorageModelsUserAssignedIdentity.  # noqa: E501
        :rtype: str
        """
        return self._principal_id

    @principal_id.setter
    def principal_id(self, principal_id):
        """Sets the principal_id of this MicrosoftAzureManagementStorageModelsUserAssignedIdentity.


        :param principal_id: The principal_id of this MicrosoftAzureManagementStorageModelsUserAssignedIdentity.  # noqa: E501
        :type: str
        """

        self._principal_id = principal_id

    @property
    def client_id(self):
        """Gets the client_id of this MicrosoftAzureManagementStorageModelsUserAssignedIdentity.  # noqa: E501


        :return: The client_id of this MicrosoftAzureManagementStorageModelsUserAssignedIdentity.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this MicrosoftAzureManagementStorageModelsUserAssignedIdentity.


        :param client_id: The client_id of this MicrosoftAzureManagementStorageModelsUserAssignedIdentity.  # noqa: E501
        :type: str
        """

        self._client_id = client_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MicrosoftAzureManagementStorageModelsUserAssignedIdentity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MicrosoftAzureManagementStorageModelsUserAssignedIdentity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
