# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MicrosoftAzureManagementStorageModelsActiveDirectoryProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'domain_name': 'str',
        'net_bios_domain_name': 'str',
        'forest_name': 'str',
        'domain_guid': 'str',
        'domain_sid': 'str',
        'azure_storage_sid': 'str',
        'sam_account_name': 'str',
        'account_type': 'str'
    }

    attribute_map = {
        'domain_name': 'domainName',
        'net_bios_domain_name': 'netBiosDomainName',
        'forest_name': 'forestName',
        'domain_guid': 'domainGuid',
        'domain_sid': 'domainSid',
        'azure_storage_sid': 'azureStorageSid',
        'sam_account_name': 'samAccountName',
        'account_type': 'accountType'
    }

    def __init__(self, domain_name=None, net_bios_domain_name=None, forest_name=None, domain_guid=None, domain_sid=None, azure_storage_sid=None, sam_account_name=None, account_type=None):  # noqa: E501
        """MicrosoftAzureManagementStorageModelsActiveDirectoryProperties - a model defined in Swagger"""  # noqa: E501
        self._domain_name = None
        self._net_bios_domain_name = None
        self._forest_name = None
        self._domain_guid = None
        self._domain_sid = None
        self._azure_storage_sid = None
        self._sam_account_name = None
        self._account_type = None
        self.discriminator = None
        if domain_name is not None:
            self.domain_name = domain_name
        if net_bios_domain_name is not None:
            self.net_bios_domain_name = net_bios_domain_name
        if forest_name is not None:
            self.forest_name = forest_name
        if domain_guid is not None:
            self.domain_guid = domain_guid
        if domain_sid is not None:
            self.domain_sid = domain_sid
        if azure_storage_sid is not None:
            self.azure_storage_sid = azure_storage_sid
        if sam_account_name is not None:
            self.sam_account_name = sam_account_name
        if account_type is not None:
            self.account_type = account_type

    @property
    def domain_name(self):
        """Gets the domain_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501


        :return: The domain_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :rtype: str
        """
        return self._domain_name

    @domain_name.setter
    def domain_name(self, domain_name):
        """Sets the domain_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.


        :param domain_name: The domain_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :type: str
        """

        self._domain_name = domain_name

    @property
    def net_bios_domain_name(self):
        """Gets the net_bios_domain_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501


        :return: The net_bios_domain_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :rtype: str
        """
        return self._net_bios_domain_name

    @net_bios_domain_name.setter
    def net_bios_domain_name(self, net_bios_domain_name):
        """Sets the net_bios_domain_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.


        :param net_bios_domain_name: The net_bios_domain_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :type: str
        """

        self._net_bios_domain_name = net_bios_domain_name

    @property
    def forest_name(self):
        """Gets the forest_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501


        :return: The forest_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :rtype: str
        """
        return self._forest_name

    @forest_name.setter
    def forest_name(self, forest_name):
        """Sets the forest_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.


        :param forest_name: The forest_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :type: str
        """

        self._forest_name = forest_name

    @property
    def domain_guid(self):
        """Gets the domain_guid of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501


        :return: The domain_guid of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :rtype: str
        """
        return self._domain_guid

    @domain_guid.setter
    def domain_guid(self, domain_guid):
        """Sets the domain_guid of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.


        :param domain_guid: The domain_guid of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :type: str
        """

        self._domain_guid = domain_guid

    @property
    def domain_sid(self):
        """Gets the domain_sid of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501


        :return: The domain_sid of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :rtype: str
        """
        return self._domain_sid

    @domain_sid.setter
    def domain_sid(self, domain_sid):
        """Sets the domain_sid of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.


        :param domain_sid: The domain_sid of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :type: str
        """

        self._domain_sid = domain_sid

    @property
    def azure_storage_sid(self):
        """Gets the azure_storage_sid of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501


        :return: The azure_storage_sid of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :rtype: str
        """
        return self._azure_storage_sid

    @azure_storage_sid.setter
    def azure_storage_sid(self, azure_storage_sid):
        """Sets the azure_storage_sid of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.


        :param azure_storage_sid: The azure_storage_sid of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :type: str
        """

        self._azure_storage_sid = azure_storage_sid

    @property
    def sam_account_name(self):
        """Gets the sam_account_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501


        :return: The sam_account_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :rtype: str
        """
        return self._sam_account_name

    @sam_account_name.setter
    def sam_account_name(self, sam_account_name):
        """Sets the sam_account_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.


        :param sam_account_name: The sam_account_name of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :type: str
        """

        self._sam_account_name = sam_account_name

    @property
    def account_type(self):
        """Gets the account_type of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501


        :return: The account_type of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :rtype: str
        """
        return self._account_type

    @account_type.setter
    def account_type(self, account_type):
        """Sets the account_type of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.


        :param account_type: The account_type of this MicrosoftAzureManagementStorageModelsActiveDirectoryProperties.  # noqa: E501
        :type: str
        """

        self._account_type = account_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MicrosoftAzureManagementStorageModelsActiveDirectoryProperties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MicrosoftAzureManagementStorageModelsActiveDirectoryProperties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
