import pandas as pd
from ._log_entry import LogEntry as LogEntry
from ._log_level import LogLevel as LogLevel
from rich.table import Table
from typing import List, Optional

class Log(List[LogEntry]):
    MAX_RECORDS: int
    def show(self) -> None: ...
    def __rich__(self) -> Table: ...
    def to_dataframe(self) -> pd.DataFrame: ...
    @staticmethod
    def tail(max_records: Optional[int] = ...) -> Log: ...
    @staticmethod
    def get(solas_id: Optional[str] = ..., max_records: Optional[int] = ..., for_display: Optional[bool] = ...) -> Log: ...
