# Generated by Django 5.2 on 2025-04-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("func_name", models.CharField(max_length=400)),
                ("queue", models.CharField(max_length=400)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=400,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("completed", models.DateTimeField(blank=True, null=True)),
                ("failed", models.DateTimeField(blank=True, null=True)),
                ("not_before", models.DateTimeField(blank=True, null=True)),
                ("raw_params", models.TextField(blank=True, null=True)),
                ("raw_returned", models.TextField(blank=True, null=True)),
                ("retry_attempts", models.IntegerField(default=0)),
                ("retry_delay", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField()),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
