# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...requests.media import MediaParams
from .media_get_response_links import MediaGetResponseLinksParams
from .media_get_response_meta import MediaGetResponseMetaParams


class MediaGetResponseParams(typing_extensions.TypedDict):
    meta: typing_extensions.NotRequired[MediaGetResponseMetaParams]
    data: typing_extensions.NotRequired[MediaParams]
    links: typing_extensions.NotRequired[MediaGetResponseLinksParams]
