# coding: utf-8

"""
    Protean API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.11
    Contact: support@cogrow.tech
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CombiningStrategy(str, Enum):
    """
    `SLIDING_WINDOW` groups sentences using a fixed-size window of consecutive sentences to create overlapping combined units. As the window slides forward one sentence at a time, it ensures smoother semantic transitions between chunks by maintaining context continuity.<br><br> `TUMBLING_WINDOW` groups sentences into fixed-size, non-overlapping combined units. Each group of sentences is used once without overlap, providing distinct, separate segments for comparison.<br><br> `ADJACENT_LINES` groups sentences with a fixed number of sentences before and after and moving one sentence ahead at a time. It creates overlapping combined units where each unit centers around a specific line, including a fixed number of neighboring lines as context.
    """

    """
    allowed enum values
    """
    SLIDING_WINDOW = 'SLIDING_WINDOW'
    TUMBLING_WINDOW = 'TUMBLING_WINDOW'
    ADJACENT_LINES = 'ADJACENT_LINES'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CombiningStrategy from a JSON string"""
        return cls(json.loads(json_str))


