# This file was auto-generated by Fern from our API Definition.

from .....core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .....core.pydantic_utilities import IS_PYDANTIC_V2


class TryProtocols(UniversalBaseModel):
    protocol: str = pydantic.Field(alias="Protocol")
    connection_data: typing.Optional[str] = pydantic.Field(alias="ConnectionData", default=None)
    errors: typing.List[str] = pydantic.Field(alias="Errors")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
