
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-08T20:34:46-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "7c2860e210254b911dc703e4ff60a319ccd9b07a",
 "version": "2.61.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
