# Generated by Django 5.1.1 on 2024-10-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("networks", "0008_host_last_config_refresh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="fw_groupss", to="networks.group"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("network", "name"), name="unique_group_name_per_network"
            ),
        ),
    ]
