# Generated by Django 5.1.7 on 2025-03-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0012_host_config_freeze_configrollout"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="is_ephemeral",
            field=models.BooleanField(
                default=False,
                help_text="When true, this host will be removed if offline for over 10 minutes",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="ephemeral_peers",
            field=models.BooleanField(
                default=False,
                help_text="When true, peers that are offline for over 10 minutes will be removed",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this key expires. Null means no expiration.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="reusable",
            field=models.BooleanField(
                default=True,
                help_text="When false, this key can not be used multiple times",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="usage_count",
            field=models.IntegerField(
                default=0, help_text="Number of times this key has been used"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="usage_limit",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum number of peers that can enroll with this key. Null means unlimited.",
                null=True,
            ),
        ),
    ]
