# Generated by Django 5.2 on 2025-05-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0022_alter_groupconfig_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description for this rule', max_length=255),
        ),
    ]
