# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CreateAssetDustBtcV1RespDetailsInner(BaseModel):
    """
    CreateAssetDustBtcV1RespDetailsInner
    """ # noqa: E501
    amount_free: Optional[StrictStr] = Field(default=None, alias="amountFree")
    asset: Optional[StrictStr] = None
    asset_full_name: Optional[StrictStr] = Field(default=None, alias="assetFullName")
    exchange: Optional[StrictStr] = None
    to_bnb: Optional[StrictStr] = Field(default=None, alias="toBNB")
    to_bnb_off_exchange: Optional[StrictStr] = Field(default=None, alias="toBNBOffExchange")
    to_btc: Optional[StrictStr] = Field(default=None, alias="toBTC")
    __properties: ClassVar[List[str]] = ["amountFree", "asset", "assetFullName", "exchange", "toBNB", "toBNBOffExchange", "toBTC"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateAssetDustBtcV1RespDetailsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateAssetDustBtcV1RespDetailsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amountFree": obj.get("amountFree"),
            "asset": obj.get("asset"),
            "assetFullName": obj.get("assetFullName"),
            "exchange": obj.get("exchange"),
            "toBNB": obj.get("toBNB"),
            "toBNBOffExchange": obj.get("toBNBOffExchange"),
            "toBTC": obj.get("toBTC")
        })
        return _obj


