# coding: utf-8

"""
    Binance Spot API

    OpenAPI specification for Binance exchange - Spot API

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from binance.spot.models.create_margin_order_oco_v1_resp_orders_inner import CreateMarginOrderOcoV1RespOrdersInner
from typing import Optional, Set
from typing_extensions import Self

class GetOpenOrderListV3RespItem(BaseModel):
    """
    GetOpenOrderListV3RespItem
    """ # noqa: E501
    contingency_type: Optional[StrictStr] = Field(default=None, alias="contingencyType")
    list_client_order_id: Optional[StrictStr] = Field(default=None, alias="listClientOrderId")
    list_order_status: Optional[StrictStr] = Field(default=None, alias="listOrderStatus")
    list_status_type: Optional[StrictStr] = Field(default=None, alias="listStatusType")
    order_list_id: Optional[StrictInt] = Field(default=None, alias="orderListId")
    orders: Optional[List[CreateMarginOrderOcoV1RespOrdersInner]] = None
    symbol: Optional[StrictStr] = None
    transaction_time: Optional[StrictInt] = Field(default=None, alias="transactionTime")
    __properties: ClassVar[List[str]] = ["contingencyType", "listClientOrderId", "listOrderStatus", "listStatusType", "orderListId", "orders", "symbol", "transactionTime"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetOpenOrderListV3RespItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in orders (list)
        _items = []
        if self.orders:
            for _item_orders in self.orders:
                if _item_orders:
                    _items.append(_item_orders.to_dict())
            _dict['orders'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetOpenOrderListV3RespItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "contingencyType": obj.get("contingencyType"),
            "listClientOrderId": obj.get("listClientOrderId"),
            "listOrderStatus": obj.get("listOrderStatus"),
            "listStatusType": obj.get("listStatusType"),
            "orderListId": obj.get("orderListId"),
            "orders": [CreateMarginOrderOcoV1RespOrdersInner.from_dict(_item) for _item in obj["orders"]] if obj.get("orders") is not None else None,
            "symbol": obj.get("symbol"),
            "transactionTime": obj.get("transactionTime")
        })
        return _obj


