# This file was auto-generated by Fern from our API Definition.

from .....core.pydantic_utilities import UniversalBaseModel
import pydantic
from .dns_record_enum import DnsRecordEnum
from .....core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class DnsZoneTransferRecord(UniversalBaseModel):
    name: str = pydantic.Field(alias="Name")
    type: DnsRecordEnum = pydantic.Field(alias="Type")
    value: str = pydantic.Field(alias="Value")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
